config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: :new
  end

  resources :posts, except: [:new, :index, :destroy] do
    resources :comments, only: :new
    post "upvote"
    post "downvote"
  end

  resources :comments, only: [:create, :show] do
    post "upvote"
    post "downvote"
  end

  root "sessions#new"
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged

  validates :title, presence: true, uniqueness: true
  validates :description, :moderator_id, presence: true

  belongs_to(
    :moderator,
    :class_name => 'User',
    :foreign_key => :moderator_id,
    :primary_key => :id
  )

  has_many :postsubs
  has_many :posts, through: :postsubs

  def posts_by_votes
    posts.sort_by { |post| post.calculate_votes }.reverse
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.friendly.find(params[:id])
  end

  def edit
    @sub = Sub.friendly.find(params[:id])
  end

  def update
    @sub = Sub.friendly.find(params[:id])
    if @sub.moderator_id != current_user.id
      flash[:error] = "You can't edit other people's subreddits!"
      redirect_to sub_url(@sub)
    elsif @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% req_url = (sub.persisted? ? sub_url(sub) : subs_url ) %>
<% req_method = (sub.persisted? ? :patch : :post ) %>
<% req_submit_value = (sub.persisted? ? "update!" : "create!" ) %>

<%= form_for(sub, url: req_url, method: req_method ) do |f| %>
Sub Title: <%= f.text_field :title %><br />
Sub Description: <%= f.text_field :description %><br />
<%= f.submit req_submit_value %>
<% end %>

app/views/subs/edit.html.erb
<h1>Edit Your Account</h1>
<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1 class="title">Subreddits</h1>
<ul>
<% @subs.each do |sub| %>
  <li><%= link_to sub.title, sub_url(sub) %>
  <%= sub.description %> </li>
<% end %>
</ul>

<%= button_to "Add a New Sub", new_sub_url, method: :get, class: "btn btn-default" %>

app/views/subs/new.html.erb
<h1>Create a Subreddit</h1>
<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>
<% if @sub.posts.any? %>
  <div class="posts">
    <% @sub.posts_by_votes.each do |post| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <% if post.url.nil? || post.url.empty? %>
          <%= link_to post.title, post_url(post) %>
        <% else %>
          <%= link_to post.title, post.url %>
        <% end %>
        | submitted
        <%= time_ago_in_words(post.created_at) %> ago by
        <%= link_to post.author.username, user_url(post.author) %>
      </div>
      <div class="panel-footer">
        <%= link_to "↑", post_upvote_url(post), method: :post %>
        <%= link_to "↓", post_downvote_url(post), method: :post %>
        <span class="label label-default vote"><%= post.calculate_votes %></span>
        <%= link_to "#{post.num_of_comments} comments", post_url(post) %>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
<p> No Posts </p>
<% end %>
<div class="btn-group pull-right">
  <%= link_to "Edit This Sub", edit_sub_url(@sub.id), class: "btn btn-default" %>
  <%= link_to "Post", new_sub_post_url(@sub.id), class: "btn btn-default btn-custom" %>
</div>