config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: :new
  end

  resources :posts, except: [:new, :index, :destroy] do
    resources :comments, only: :new
    post "upvote"
    post "downvote"
  end

  resources :comments, only: [:create, :show] do
    post "upvote"
    post "downvote"
  end

  root "sessions#new"
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged

  validates :title, :author_id, presence: true

  has_many :postsubs, inverse_of: :post
  has_many :subs, through: :postsubs
  has_many :comments
  has_many :votes, as: :votable
  belongs_to :author, class_name: 'User'

  def comments_by_parent_id
    comment_hash = Hash.new { [] }
    self.comments.each do |comment|
      comment_hash[comment.parent_comment_id] <<= comment
    end

    comment_hash.values.each do |array|
      array.sort! { |comment1, comment2| comment2.calculate_votes <=> comment1.calculate_votes }
    end

    comment_hash
  end

  def num_of_comments
    comments.size
  end

  def calculate_votes
    return 0 if votes.empty?
    self.votes.map{ |vote| vote.value }.inject(&:+)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def new
    @post = Post.new
    @post.sub_ids = [params[:sub_id]]
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.sub_ids = params[:post][:sub_ids]

    if @post.sub_ids.empty?
      flash[:errors] = "You need to assign a subreddit"
      render :new
    elsif @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
    @all_comments = @post.comments_by_parent_id
  end

  def edit
    @post = Post.friendly.find(params[:id])
    if @post.author_id != current_user.id
      flash[:error] = "You can't edit other people's posts!"
      redirect_to post_url(@post)
    else
      @post = Post.find(params[:id])
    end
  end

  def update
    @post = Post.friendly.find(params[:id])
    @post.sub_ids = params[:post][:sub_ids]
    if @post.author_id != current_user.id
      flash[:error] = "You can't edit other people's posts!"
      redirect_to post_url(@post)
    elsif @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def index
    @posts = post.all
  end

  def upvote
    vote = Vote.new(value: 1, voter_id: current_user.id,
                  votable_type: 'Post', votable_id: params[:post_id])
    if vote.save
      redirect_to post_url(vote.votable)
    else
      flash[:errors] = vote.errors.full_messages
      redirect_to post_url(vote.votable)
    end
  end

  def downvote
    vote = Vote.new(value: -1, voter_id: current_user.id,
                    votable_type: 'Post', votable_id: params[:post_id])
    if vote.save
      redirect_to post_url(vote.votable)
    else
      flash[:errors] = vote.errors.full_messages
      redirect_to post_url(vote.votable)
    end
  end

  # def destroy
  #   @post = Post.find(params[:id])
  #   if @post.author_id != current_user.id
  #     flash[:error] = "You can't delete other people's posts!"
  #     redirect_to post_url(@post)
  #   else
  #     @post.destroy
  #     redirect_to sub_url(@post.sub)
  #   end
  # end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<ul class="comments">
  <%= link_to comment.content, comment_url(comment) %><br />
  by <%= comment.commenter.username %> |
  <%= link_to "↑", comment_upvote_url(comment.id), method: :post %>
  <%= link_to "↓", comment_downvote_url(comment.id), method: :post %>
  <span class="label label-default vote"><%= comment.calculate_votes %></span>

  <% if @all_comments[comment.id].any? %>
    <% @all_comments[comment.id].each do |child_comment| %>
      <li class="comments"><%= render "comment", comment: child_comment %></li>
    <% end %>
  <% end %>
</ul>

app/views/posts/_form.html.erb
<% req_url = (post.persisted? ? post_url(post) : posts_url ) %>
<% req_method = (post.persisted? ? :patch : :post ) %>
<% req_submit_value = (post.persisted? ? "update!" : "create!" ) %>

<%= form_for(post, url: req_url, method: req_method ) do |f| %>
Post Title: <%= f.text_field :title %><br />
Post Content (optional): <%= f.text_area :content %><br />
Post URL (optional): <%= f.text_field :url %><br />
<br>
Subs:<br>
<% Sub.all.each do |sub|  %>
  <label><%= check_box_tag :sub_ids, sub.id, post.subs.include?(sub), :name => 'post[sub_ids][]'  %><u><%= sub.title %></u></label><br>
<% end %>

<%= hidden_field_tag :sub_id, params[:sub_id] %>
<%= f.submit req_submit_value %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Your Post</h1>
<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1>Create a Post</h1>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h1><%= @post.title %></h1>
  <div>
    Subreddits:
  <% @post.subs.each do |sub| %>
    <span class="label label-default"><%= link_to sub.title, sub_url(sub) %></span>
  <% end %>
  </div>

  <% unless @post.content.nil? %>
    <p><%= @post.content %></p>
  <% end %>

  <% unless @post.url.nil? || @post.url.empty? %>
  <%= link_to "(#{@post.url})", @post.url %></p>
  <% end %>
</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">

  <% if @all_comments.any? %>
  <h4>Comments</h4>
  <ul class="list-unstyled comments">
    <% @all_comments[nil].each do |top_comment| %>
        <li class="comments"><%= render "comment", comment: top_comment %></li>
      <% end %>
  </ul>
  <% end %>
</div>
</div>
  <% if current_user %>
    <div class="input-group">
      <h4>New Comment</h4>
      <%= form_for(Comment.new, url: comments_url, method: :create ) do |f| %>
      <%= f.text_area :content %><br />

      <%= hidden_field_tag :commenter_id, current_user.id %>
      <%= hidden_field_tag :post_id, params[:id] %>
      <%= f.submit "New Comment" %>
      <% end %>
    </div>
  <% end %>




<%= button_to "Edit the Post", edit_post_url(@post.id), method: :get, class: "btn btn-default" %>