config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: :new
  end

  resources :posts, except: [:new, :index, :destroy] do
    resources :comments, only: :new
    post "upvote"
    post "downvote"
  end

  resources :comments, only: [:create, :show] do
    post "upvote"
    post "downvote"
  end

  root "sessions#new"
end

app/views/layouts/_errors.html.erb
<%- if flash.any? %>
<%- flash.keys.each do |flash_key| %>
<%- next if flash_key.to_s == 'timedout' %>
<div class="alert-message <%= flash_key %>">
  <%= flash.discard(flash_key) %>
</div>
<%- end %>
<%- end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li><%= link_to "Home", subs_url %></li>

          <% if current_user %>

            <li><%= link_to "Profile", user_url(current_user) %></li>
            <li><%= link_to "Log out", session_url, method: :delete %></li>

          <% else %>

            <li><%= link_to "Sign in", new_session_url %></li>
            <li><%= link_to "Sign up", new_user_url %></li>

          <% end %>

        </ul>
      </div>
    </div>

  <%= render "/layouts/errors" %>
    <%= yield %>
  </div>
</body>
</html>